version: '3'

services:
  interactiveipheatmap:
    image: interactiveipheatmap
    environment:
      - DEBUG=True
      - PROD_HOST=https://localhost
      - SECRET_KEY=insecure_dev_key
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
