version: '3'
# Override Env vars with passwords only used for local dev
services:
  db:
    environment:
      - POSTGRES_PASSWORD=insecure_dev_pass

  interactiveipheatmap:
    environment:
      - DB_PASSWORD=insecure_dev_pass
      - DEBUG=True
      - PROD_HOST=localhost
      # Doesn't matter because this is just for local dev env
      - SECRET_KEY=SgjVVL/FHZc35mn8SHF99Z6JM1dygopTwiP4H2ba+UjbIxnrlb