version: '3'

services:
  db:
    build: ./db
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    expose:
      - "5432"
    ports:
      - 5432:5432
    networks:
      - app-network

  interactiveipheatmap:
    image: interactiveipheatmap
    environment:
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PORT=5432
      - DB_HOST=db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: