# Generated by Django 3.1.5 on 2021-02-02 23:10

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_heatmap_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='network',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
    ]
