# Generated by Django 3.1.5 on 2021-02-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_heatmap_api', '0004_auto_20210204_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='c',
            field=models.IntegerField(default=0),
        ),
    ]
