# Generated by Django 3.1.5 on 2022-03-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
