# Generated by Django 3.1.5 on 2021-02-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_heatmap_api', '0002_auto_20210202_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='c',
            field=models.FloatField(default=0.0),
        ),
    ]
