# Generated by Django 3.1.5 on 2021-02-04 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_heatmap_api', '0003_ipaddress_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='position',
            new_name='p',
        ),
    ]
